import Footer from "@/components/custom/footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Token System",
  description: "Generated by create next app",
};

export default function EnglishLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <main className="flex flex-col flex-grow justify-start items-center w-full h-full pt-24 px-32 gap-16">
        {children}
      </main>
      <Footer />
    </>
  );
}
