export const metadata = {
  title: "API",
  description: "Generated by Next.js",
};

export default function ApiLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
